name: Pylint and Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: django_db
          POSTGRES_USER: django_user
          POSTGRES_PASSWORD: django_password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd django_back
          pip install -r requirements.txt

      - name: Wait for PostgreSQL
        run: |
          while ! pg_isready -h localhost -p 5432 > /dev/null 2> /dev/null; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 1
          done

      - name: Run migrations
        run: |
          cd django_back
          python manage.py migrate

      - name: Analysing the code with pylint
        run: |
          pylint --rcfile=pyling_rc_config $(git ls-files '*.py')

      - name: Run tests
        env:
          DJANGO_DB_NAME: django_db
          DJANGO_DB_USER: django_user
          DJANGO_DB_PASSWORD: django_password
          DJANGO_DB_HOST: localhost
          DJANGO_DB_PORT: 5432
        run: |
          cd django_back
          python manage.py test --verbosity=2
